openapi: 3.2.0
info:
  title: Rekor Pubkey API
  description: Rekor is a cryptographically secure, immutable transparency log for signed software releases.
  version: 1.0.0
servers:
- url: http://rekor.sigstore.dev
tags:
- name: pubkey
paths:
  /api/v1/log/publicKey:
    get:
      summary: Retrieve the public key that can be used to validate the signed tree head
      description: Returns the public key that can be used to validate the signed tree head
      operationId: getPublicKey
      tags:
      - pubkey
      parameters:
      - in: query
        name: treeID
        description: The tree ID of the tree you wish to get a public key for
        schema:
          type: string
          pattern: ^[0-9]+$
      responses:
        200:
          description: The public key
          content:
            application/x-pem-file:
              schema:
                type: string
        default:
          $ref: '#/components/responses/InternalServerError'
components:
  responses:
    InternalServerError:
      description: There was an internal error in the server while processing the request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
  schemas:
    Error:
      type: object
      properties:
        code:
          type: integer
        message:
          type: string
