swagger: '2.0'
info:
  title: Fulcio CA pubkey API
  version: 2.0.0
  contact:
    name: sigstore Fulcio project
    url: https://github.com/sigstore/fulcio
    email: sigstore-dev@googlegroups.com
  license:
    name: Apache License 2.0
    url: https://github.com/sigstore/fulcio/blob/main/LICENSE
host: fulcio.sigstore.dev
schemes:
- http
consumes:
- application/json
produces:
- application/json
tags:
- name: pubkey
paths:
  /api/v1/log/publicKey:
    get:
      summary: Retrieve the public key that can be used to validate the signed tree head
      description: Returns the public key that can be used to validate the signed tree head
      operationId: getPublicKey
      tags:
      - pubkey
      parameters:
      - in: query
        name: treeID
        type: string
        pattern: ^[0-9]+$
        description: The tree ID of the tree you wish to get a public key for
      produces:
      - application/x-pem-file
      responses:
        200:
          description: The public key
          schema:
            type: string
        default:
          $ref: '#/responses/InternalServerError'
definitions:
  Error:
    type: object
    properties:
      code:
        type: integer
      message:
        type: string
responses:
  InternalServerError:
    description: There was an internal error in the server while processing the request
    schema:
      $ref: '#/definitions/Error'
externalDocs:
  description: More about Fulcio
  url: https://github.com/sigstore/fulcio
